import { useEffect, useState } from 'react';

const REPO = 'https://github.com/Tzinny-dev/sprout-toolkit';
const PYPI = 'https://pypi.org/project/sprout-toolkit/';

const features = [
  {
    title: 'Deterministic procgen',
    body: 'Numeric seeds → reproducible assets. Same seed, same pixels, testable in CI.',
  },
  {
    title: '8-bit autotile',
    body: '16/47-variant autotiling with bitmask lookup and a canonicalMask helper.',
  },
  {
    title: 'Bitmap fonts from TTF',
    body: 'Glyph atlas with advance metrics — no native text layout needed.',
  },
  {
    title: 'Runtime SkSL shaders',
    body: 'Tileable FBM value-noise shaders for runtime variation, zero bundle weight.',
  },
  {
    title: 'Wired index.ts',
    body: "Typed helpers for react-native-skia's <Atlas>: rect buffers, glyph layout, batch paths.",
  },
  {
    title: 'QA built in',
    body: 'sprout lint / diff / watch — atlas waste, empty frames, CRC build comparison, hot reload.',
  },
];

const SPEC_EXAMPLE = `{
  "name": "props_atlas",
  "seed": 2024,
  "layout": { "framePx": 64, "cols": 6, "tileLogical": 32, "sample": "nearest" },
  "items": [
    { "id": "rock",  "generator": "props", "frames": 6, "params": { "kind": "rock" } },
    { "id": "chest", "generator": "props", "frames": 4, "params": { "kind": "chest" } }
  ]
}`;

export function Home() {
  const [version, setVersion] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    // PyPI JSON API has CORS enabled; fall back silently if offline.
    fetch('https://pypi.org/pypi/sprout-toolkit/json')
      .then((r) => (r.ok ? r.json() : Promise.reject()))
      .then((data) => setVersion(data.info.version))
      .catch(() => setVersion(null));
  }, []);

  async function copyInstall() {
    await navigator.clipboard.writeText('pip install sprout-toolkit');
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <div className="space-y-24">
      {/* Hero */}
      <section className="text-center space-y-6">
        <p className="inline-block rounded-full border border-brand-700 bg-brand-950 px-4 py-1 text-sm text-brand-300">
          {version ? `v${version} on PyPI` : 'MIT licensed'} · Python 3.10–3.13
        </p>
        <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-white">
          Grow your 2D assets procedurally 🌱
        </h1>
        <p className="mx-auto max-w-2xl text-lg text-slate-400">
          Deterministic spritesheets, autotiles, bitmap fonts and SkSL shaders
          for Expo + react-native-skia — all from JSON specs. Same seed, same
          pixels, testable in CI.
        </p>
        <div className="flex flex-wrap justify-center gap-3">
          <button
            onClick={copyInstall}
            className="rounded-md bg-brand-500 px-5 py-2.5 font-mono text-sm text-white transition hover:bg-brand-400"
            title="Click to copy"
          >
            {copied ? 'copied ✓' : 'pip install sprout-toolkit'}
          </button>
          <a
            href={REPO}
            target="_blank"
            rel="noreferrer"
            className="rounded-md border border-slate-700 px-5 py-2.5 text-sm text-slate-200 transition hover:border-slate-500"
          >
            GitHub →
          </a>
        </div>
        <div className="flex flex-wrap justify-center gap-4 text-sm text-slate-500">
          <a href={PYPI} target="_blank" rel="noreferrer" className="hover:text-slate-300">
            PyPI
          </a>
          <span>·</span>
          <a href={`${REPO}/actions`} target="_blank" rel="noreferrer" className="hover:text-slate-300">
            CI (3.10–3.13)
          </a>
          <span>·</span>
          <span>145 tests</span>
        </div>
      </section>

      {/* Showcase GIFs */}
      <section className="grid gap-6 sm:grid-cols-2">
        <figure className="rounded-lg border border-slate-800 bg-black/30 p-4 text-center">
          <img
            src="/showcase/hero_walk.gif"
            alt="8-frame blob walk cycle generated by sprout"
            className="mx-auto image-rendering-pixelated"
            loading="lazy"
          />
          <figcaption className="mt-3 text-sm text-slate-400">
            <code className="text-brand-300">blob_walk</code> — 8-frame walk cycle
          </figcaption>
        </figure>
        <figure className="rounded-lg border border-slate-800 bg-black/30 p-4 text-center">
          <img
            src="/showcase/spark.gif"
            alt="Animated spark burst generated by sprout"
            className="mx-auto"
            loading="lazy"
          />
          <figcaption className="mt-3 text-sm text-slate-400">
            <code className="text-brand-300">particles/spark</code> — animated burst
          </figcaption>
        </figure>
        <figure className="rounded-lg border border-slate-800 bg-black/30 p-4 text-center sm:col-span-2">
          <img
            src="/showcase/island.png"
            alt="47-variant autotile island generated by sprout"
            className="mx-auto"
            loading="lazy"
          />
          <figcaption className="mt-3 text-sm text-slate-400">
            <code className="text-brand-300">autotile 47</code> — island via bitmask lookup
          </figcaption>
        </figure>
      </section>

      {/* Features */}
      <section>
        <h2 className="text-2xl font-semibold text-white mb-8">What it generates</h2>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => (
            <div
              key={f.title}
              className="rounded-lg border border-slate-800 bg-slate-900/50 p-5"
            >
              <h3 className="font-medium text-brand-300">{f.title}</h3>
              <p className="mt-2 text-sm text-slate-400">{f.body}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Spec example */}
      <section className="grid gap-8 lg:grid-cols-2 items-start">
        <div>
          <h2 className="text-2xl font-semibold text-white">Assets as code</h2>
          <p className="mt-3 text-slate-400">
            Every asset is a JSON spec + a numeric seed. Each run emits{' '}
            <code className="text-brand-300">atlas.png</code> +{' '}
            <code className="text-brand-300">manifest.json</code> + a typed{' '}
            <code className="text-brand-300">index.ts</code> wired for
            react-native-skia. Diff builds in CI by CRC; the manifest records the
            generator version that produced it.
          </p>
          <a
            href="/docs"
            className="mt-5 inline-block text-brand-400 hover:text-brand-300"
          >
            10-minute tutorial (pip → sprites on screen) →
          </a>
        </div>
        <pre className="overflow-x-auto rounded-lg border border-slate-800 bg-black/40 p-5 text-sm text-slate-300">
          <code>{SPEC_EXAMPLE}</code>
        </pre>
      </section>
    </div>
  );
}
