"""SkSL emitter (opt-in runtime mode) — INVESTIGACION.md §6.

Generates a deterministic SkSL shader (fixed template + uniforms derived
from the spec's seed) that reproduces the bake's FBM terrain on-device,
without bloating the bundle with PNGs. Consumed with::

    const effect = Skia.RuntimeEffect.Make(SHADER_SKS);
    <Shader source={effect} uniforms={shaderUniformsAt(t)} />

The ``.sksl`` file is written alongside the atlas for versioning/inspection;
the generated ``index.ts`` embeds the same source as ``SHADER_SKS`` (template
literal) so no extra Metro configuration is required.
"""
from __future__ import annotations

MAX_OCTAVES = 8

DEFAULTS: dict = {
    "freq": 0.05,
    "octaves": 4,
    "tileable": True,
    # Endpoints of the `terrain` palette (0..1) as a base/accent blend.
    "base": [0.16, 0.27, 0.16],
    "accent": [0.90, 0.79, 0.46],
}

# Fixed template: the source does NOT depend on the seed (it lives in the
# uniforms), so it is byte-identical across regenerations. No backticks or
# `${` so it can be embedded in a TypeScript template literal.
TEMPLATE = """// GENERATED by sprout — runtime terrain shader (FBM value-noise, tileable).
// Uniforms generated from the spec (see manifest.json > shader.uniforms).
uniform float u_freq;
uniform float u_oct;
uniform float u_seed;
uniform float2 u_tile;
uniform float u_time;
uniform float3 u_base;
uniform float3 u_accent;

float hash(float2 p) {
  return fract(sin(dot(p + u_seed, float2(127.1, 311.7))) * 43758.5453123);
}

float vnoise(float2 p) {
  float2 period = u_tile * u_freq;
  float2 i = floor(p);
  float2 f = fract(p);
  float2 u = f * f * (3.0 - 2.0 * f);
  float2 a = mod(i, period);
  float2 b = mod(i + float2(1.0, 0.0), period);
  float2 c = mod(i + float2(0.0, 1.0), period);
  float2 d = mod(i + float2(1.0, 1.0), period);
  float n00 = hash(a);
  float n10 = hash(b);
  float n01 = hash(c);
  float n11 = hash(d);
  return mix(mix(n00, n10, u.x), mix(n01, n11, u.x), u.y);
}

float fbm(float2 p) {
  float v = 0.0;
  float amp = 0.5;
  float2 q = p;
  for (int k = 0; k < 8; k++) {
    if (float(k) < u_oct) {
      v += vnoise(q) * amp;
    }
    q = q * 2.03 + float2(17.3, 9.1);
    amp *= 0.5;
  }
  return v;
}

half4 main(float2 xy) {
  float2 p = xy * u_freq + float2(u_time * 0.02, 0.0);
  float n = fbm(p) * 0.85 + 0.075;
  float3 col = mix(u_base, u_accent, clamp(n, 0.0, 1.0));
  return half4(col, 1.0);
}
"""


def normalize_params(raw: bool | dict | None) -> dict | None:
    """Normalize the spec's ``runtime`` field into params or ``None``."""
    if raw is None or raw is False:
        return None
    params = dict(DEFAULTS)
    if raw is True:
        return params
    if not isinstance(raw, dict):
        raise ValueError(f"runtime must be true/false or an object, received {raw!r}")
    for key in ("freq", "octaves", "tileable", "base", "accent"):
        if key in raw:
            params[key] = raw[key]
    freq = float(params["freq"])
    if freq <= 0:
        raise ValueError(f"runtime.freq must be > 0 (received {raw.get('freq')!r})")
    octaves = int(params["octaves"])
    if not 1 <= octaves <= MAX_OCTAVES:
        raise ValueError(
            f"runtime.octaves must be within 1..{MAX_OCTAVES} "
            f"(received {raw.get('octaves')!r})"
        )
    params["freq"] = freq
    params["octaves"] = octaves
    params["tileable"] = bool(params["tileable"])
    for key in ("base", "accent"):
        col = [float(c) for c in params[key]]
        if len(col) != 3 or any(not 0.0 <= c <= 1.0 for c in col):
            raise ValueError(f"runtime.{key} must be a 3-channel RGB in 0..1")
        params[key] = col
    unknown = set(raw) - {"freq", "octaves", "tileable", "base", "accent"}
    if unknown:
        raise ValueError(f"runtime has unknown keys: {sorted(unknown)}")
    return params


def build_uniforms(seed: int, params: dict, frame_px: int) -> dict:
    """Shader uniforms derived from the seed (deterministic)."""
    period = max(1, round(frame_px * float(params["freq"])))
    return {
        "freq": float(params["freq"]),
        "octaves": int(params["octaves"]),
        "seed": seed % 2**31,
        "tileable": bool(params["tileable"]),
        "tileWidth": frame_px,
        "tileHeight": frame_px,
        "period": period,
        "time": 0.0,
        "base": [float(c) for c in params["base"]],
        "accent": [float(c) for c in params["accent"]],
    }


def render_shader() -> str:
    """SkSL source (fixed template + version header)."""
    from . import __version__

    return f"// sprout {__version__} — seed in uniforms (manifest.json > shader.uniforms)\n{TEMPLATE}"
