"""SkSL emitter (opt-in runtime mode) — INVESTIGACION.md §6.

Generates a deterministic SkSL shader (fixed template + uniforms derived
from the spec's seed) that reproduces the bake's FBM terrain on-device,
without bloating the bundle with PNGs. Consumed with::

    const effect = Skia.RuntimeEffect.Make(SHADER_SKS);
    <Shader source={effect} uniforms={shaderUniformsAt(t)} />

The ``.sksl`` file is written alongside the atlas for versioning/inspection;
the generated ``index.ts`` embeds the same source as ``SHADER_SKS`` (template
literal) so no extra Metro configuration is required.
"""
from __future__ import annotations

MAX_OCTAVES = 8

DEFAULTS: dict = {
    "freq": 0.05,
    "octaves": 4,
    "tileable": True,
    # Endpoints of the `terrain` palette (0..1) as a base/accent blend.
    "base": [0.16, 0.27, 0.16],
    "accent": [0.90, 0.79, 0.46],
}

# Fixed template: the source does NOT depend on the seed (it lives in the
# uniforms), so it is byte-identical across regenerations. No backticks or
# `${` so it can be embedded in a TypeScript template literal.
TEMPLATE = """// GENERATED by sprout — runtime terrain shader (FBM value-noise, tileable).
// Uniforms generated from the spec (see manifest.json > shader.uniforms).
uniform float u_freq;
uniform float u_oct;
uniform float u_seed;
uniform float2 u_tile;
uniform float u_time;
uniform float3 u_base;
uniform float3 u_accent;

float hash(float2 p) {
  return fract(sin(dot(p + u_seed, float2(127.1, 311.7))) * 43758.5453123);
}

float vnoise(float2 p) {
  float2 period = u_tile * u_freq;
  float2 i = floor(p);
  float2 f = fract(p);
  float2 u = f * f * (3.0 - 2.0 * f);
  float2 a = mod(i, period);
  float2 b = mod(i + float2(1.0, 0.0), period);
  float2 c = mod(i + float2(0.0, 1.0), period);
  float2 d = mod(i + float2(1.0, 1.0), period);
  float n00 = hash(a);
  float n10 = hash(b);
  float n01 = hash(c);
  float n11 = hash(d);
  return mix(mix(n00, n10, u.x), mix(n01, n11, u.x), u.y);
}

float fbm(float2 p) {
  float v = 0.0;
  float amp = 0.5;
  float2 q = p;
  for (int k = 0; k < 8; k++) {
    if (float(k) < u_oct) {
      v += vnoise(q) * amp;
    }
    q = q * 2.03 + float2(17.3, 9.1);
    amp *= 0.5;
  }
  return v;
}

half4 main(float2 xy) {
  float2 p = xy * u_freq + float2(u_time * 0.02, 0.0);
  float n = fbm(p) * 0.85 + 0.075;
  float3 col = mix(u_base, u_accent, clamp(n, 0.0, 1.0));
  return half4(col, 1.0);
}
"""


def normalize_params(raw: bool | dict | None) -> dict | None:
    """Normalize the spec's ``runtime`` field into params or ``None``."""
    if raw is None or raw is False:
        return None
    params = dict(DEFAULTS)
    if raw is True:
        return params
    if not isinstance(raw, dict):
        raise ValueError(f"runtime must be true/false or an object, received {raw!r}")
    for key in ("freq", "octaves", "tileable", "base", "accent"):
        if key in raw:
            params[key] = raw[key]
    freq = float(params["freq"])
    if freq <= 0:
        raise ValueError(f"runtime.freq must be > 0 (received {raw.get('freq')!r})")
    octaves = int(params["octaves"])
    if not 1 <= octaves <= MAX_OCTAVES:
        raise ValueError(
            f"runtime.octaves must be within 1..{MAX_OCTAVES} "
            f"(received {raw.get('octaves')!r})"
        )
    params["freq"] = freq
    params["octaves"] = octaves
    params["tileable"] = bool(params["tileable"])
    for key in ("base", "accent"):
        col = [float(c) for c in params[key]]
        if len(col) != 3 or any(not 0.0 <= c <= 1.0 for c in col):
            raise ValueError(f"runtime.{key} must be a 3-channel RGB in 0..1")
        params[key] = col
    unknown = set(raw) - {"freq", "octaves", "tileable", "base", "accent"}
    if unknown:
        raise ValueError(f"runtime has unknown keys: {sorted(unknown)}")
    return params


def build_uniforms(seed: int, params: dict, frame_px: int) -> dict:
    """Shader uniforms derived from the seed (deterministic)."""
    period = max(1, round(frame_px * float(params["freq"])))
    return {
        "freq": float(params["freq"]),
        "octaves": int(params["octaves"]),
        "seed": seed % 2**31,
        "tileable": bool(params["tileable"]),
        "tileWidth": frame_px,
        "tileHeight": frame_px,
        "period": period,
        "time": 0.0,
        "base": [float(c) for c in params["base"]],
        "accent": [float(c) for c in params["accent"]],
    }


def render_shader() -> str:
    """SkSL source (fixed template + version header)."""
    from . import __version__

    return f"// sprout {__version__} — seed in uniforms (manifest.json > shader.uniforms)\n{TEMPLATE}"


# ---------------------------------------------------------------------------
# Tier effect templates (hueco B3): overlays drawn on top of sprites.
# Like TEMPLATE, sources carry no backticks/`${` so index.ts can embed
# them as string literals. `invisible` is the trivial alpha-0 helper.

TIER_TEMPLATES = ("holographic", "neon", "legend-glow", "invisible")

TIER_DEFAULTS: dict[str, dict] = {
    "holographic": {"speed": 0.35, "glow": 0.5},
    "neon": {"speed": 1.5, "glow": 0.6},
    "legend-glow": {"speed": 1.0, "glow": 0.4},
    "invisible": {},
}

_TIER_BODIES: dict[str, str] = {
    "holographic": """half4 main(float2 xy) {
  float t = u_time * u_speed + u_seed * 0.001;
  float band = sin((xy.x + xy.y) * 0.06 + t * 2.0) * 0.5 + 0.5;
  float hue = fract(band + (xy.x - xy.y) * 0.002 + t * 0.1);
  float3 col = 0.5 + 0.5 * cos(6.28318 * (hue + float3(0.0, 0.33, 0.67)));
  float alpha = 0.35 + 0.3 * sin((xy.x - xy.y) * 0.04 - t);
  return half4(col, clamp(alpha, 0.0, 1.0) * u_glow);
}""",
    "neon": """half4 main(float2 xy) {
  float t = u_time * u_speed + u_seed * 0.001;
  float pulse = 0.5 + 0.5 * sin(t * 3.0);
  float line = abs(sin(xy.x * 0.07 + t) * sin(xy.y * 0.07 - t * 0.7));
  float glow = pow(1.0 - line, 6.0);
  float3 col = float3(0.2, 1.0, 0.9) * (0.7 + 0.3 * pulse);
  return half4(col, glow * u_glow * (0.5 + 0.5 * pulse));
}""",
    "legend-glow": """half4 main(float2 xy) {
  float t = u_time * u_speed + u_seed * 0.001;
  float breathe = 0.5 + 0.5 * sin(t * 1.5);
  float3 col = float3(1.0, 0.85, 0.4);
  float g = fract(sin(dot(floor(xy * 0.25), float2(12.9898, 78.233)) + t) * 43758.5453);
  float sparkle = step(0.985, g) * (0.5 + 0.5 * sin(t * 9.0));
  float alpha = u_glow * (0.3 + 0.5 * breathe) + sparkle * 0.4;
  return half4(col, clamp(alpha, 0.0, 0.85));
}""",
    "invisible": """half4 main(float2 xy) {
  return half4(0.0, 0.0, 0.0, 0.0);
}""",
}


def normalize_tiers(raw: object) -> dict[str, dict] | None:
    """Normalize the spec's ``tiers`` block: name -> {template, params}."""
    if raw is None or raw is False:
        return None
    if not isinstance(raw, dict) or not raw:
        raise ValueError(
            f"tiers must be a non-empty object of name -> template, "
            f"received {raw!r}")
    import re

    out: dict[str, dict] = {}
    for name, rule in raw.items():
        if not re.fullmatch(r"[A-Za-z0-9_-]{1,32}", str(name)):
            raise ValueError(
                f"invalid tier name {name!r} in tiers "
                f"(use [A-Za-z0-9_-], max 32)")
        if isinstance(rule, str):
            rule = {"template": rule}
        if not isinstance(rule, dict) or "template" not in rule:
            raise ValueError(
                f"tiers.{name} must be a template name or "
                f"{{'template': ...}}, received {raw.get(name)!r}")
        template = str(rule["template"])
        if template not in TIER_TEMPLATES:
            raise ValueError(
                f"invalid tiers.{name}.template {template!r} "
                f"(available: {', '.join(TIER_TEMPLATES)})")
        params = dict(TIER_DEFAULTS[template])
        unknown_params = set(rule) - {"template"}
        for key in unknown_params:
            if key not in TIER_DEFAULTS[template]:
                raise ValueError(
                    f"tiers.{name} has unknown key {key!r} "
                    f"(template '{template}' accepts: "
                    f"{', '.join(sorted(TIER_DEFAULTS[template])) or 'none'})")
        for key in unknown_params:
            params[key] = float(rule[key])
        if params.get("speed", 0.0) < 0:
            raise ValueError(f"tiers.{name}.speed must be >= 0")
        if not 0.0 <= params.get("glow", 0.0) <= 1.0:
            raise ValueError(f"tiers.{name}.glow must be within 0..1")
        out[str(name)] = {"template": template, "params": params}
    return out


def tier_shader(seed: int, template: str, params: dict) -> dict:
    """Uniforms for one tier shader (seed-derived, deterministic)."""
    return {
        "seed": seed % 2**31,
        "time": 0.0,
        **{k: float(v) for k, v in params.items()},
    }


def render_tier_shader(template: str) -> str:
    """SkSL source for a tier template (fixed body + header)."""
    from . import __version__

    header = (
        f"// sprout {__version__} — tier template: {template} "
        f"(uniforms in manifest.json > tiers.<name>.uniforms)"
    )
    uniforms = (
        "uniform float u_seed;\nuniform float u_time;\n"
        + "".join(
            f"uniform float u_{k};\n"
            for k in sorted(TIER_DEFAULTS[template])
        )
    )
    return f"{header}\n{uniforms}{_TIER_BODIES[template]}\n"


def tier_shader_filename(spec_name: str, tier_name: str) -> str:
    return f"{spec_name}.{tier_name}.sksl"
